### ISSUE TITLE
Doesn't work on thinkpad t480

### ISSUE THREAD

**Issue by amosbird** [daveriedstra/draggy#2]
I'm trying this promising script on my arch box on thinkpad t480, however it doesn't work as it does literally nothing. Three finger drag doesn't generate any noticeable events to me.

>  If it doesn't for you, please file an issue with as much documentation as you can so that I can try to fix it.

I'm very unfamiliar with libinput and uinput, what information should I provide? Thanks!

**Comment by amosbird** [comment]
`libinput list-devices`

```
Device:           SynPS/2 Synaptics TouchPad
Kernel:           /dev/input/event12
Group:            11
Seat:             seat0, default
Size:             98x65mm
Capabilities:     pointer gesture
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge
Click methods:    *button-areas clickfinger
Disable-w-typing: enabled
Accel profiles:   none
Rotation:         n/a
```

**Comment by daveriedstra** [comment]
I just pushed a change that had been sitting on my t580 for a while, try it now! I also have the synaptics touchpad so it should work. Let me know if you have trouble.

**Comment by daveriedstra** [comment]
Oh I should also mention I've discovered that the /dev/input address of the device changes occasionally, so an autostart script won't be super reliable. An autodetect touchpad feature is coming in draggy eventually.

**Comment by amosbird** [comment]
Yeah, it now works as expected. However that `-l` lock option doesn't work well. Cursor jumps around when   doing drags after the first one.  https://la.wentropy.com/yW-8.webm

**Comment by daveriedstra** [comment]
Moved locked drag jumpiness to its own issue; closing this issue as the original problem has been fixed.
